### ISSUE TITLE
convexhullPolygon

### ISSUE THREAD

**Issue by nyanloutre** [UTBroM/GeometricLib#20]
convexhullPolygon : Polygon → Polygon, computes the convex hull of the specified polygon using the Graham’s method

**Comment by nyanloutre** [comment]
arrète de fermer les trucs qui marchent pas :)

**Comment by nyanloutre** [comment]
(outpoly.head->next->value.x - outpoly.head->value.x) * (inpoly.head->value.y - outpoly.head->next->value.y) - (inpoly.head->value.x - outpoly.head->next->value.x) * (outpoly.head->next->value.y - outpoly.head->value.y) calcul du produit vectoriel

**Comment by Vskilet** [comment]
Ouff ! finaly we can do it
